### ISSUE TITLE
postprocess has not run cleanly on this repo for eight days

### ISSUE THREAD

**Issue by grempe** [githubocto/flat-demo-bitcoin-price#11]
This repo, the demo for flat data, has not run its postprocess action cleanly for 8 days at the time of this writing.

https://github.com/githubocto/flat-demo-bitcoin-price/actions

**Comment by irealva** [comment]
Thanks for reporting. We had fixed the issue on the main Flat action but not updated the examples. Should be running smoothly now again.

Original issue: [https://github.com/githubocto/flat/issues/45](https://github.com/githubocto/flat/issues/45)

**Comment by cfjedimaster** [comment]
I'm trying to use the code for my own demo - if I wanted to see the fix, where would I find it?

**Comment by cfjedimaster** [comment]
nm - figured it out by looking at the updated code here - sorry and thank you.
