### ISSUE TITLE
trying to removing the file throws error

### ISSUE THREAD

**Issue by Ambrosiani** [githubocto/flat-demo-bitcoin-price#4]
hi, the action fails when uncommenting the last line in the postprocessing example:

https://github.com/githubocto/flat-demo-bitcoin-price/blob/5f14aad430146f25827bcd3fba5d35dc3be8388e/postprocess.js#L25

the error: `Workflow failed! ENOENT: no such file or directory, stat 'btc-price.json'`

**Comment by irealva** [comment]
Thanks for reporting this. Will be fixed as soon as we merge: [https://github.com/githubocto/flat/pull/11](https://github.com/githubocto/flat/pull/11)

**Comment by irealva** [comment]
This should work now!

**Comment by Ambrosiani** [comment]
yes it does 🎉
